Blog
front-end-by-rimantas/7-grupe-portfolio pull request #19
Opened 2019-05-08 12:06 UTC by belauzas

Truksta normalesnio stiliaus, reikia padaryti su atskira uzduotimi

2019-05-08 12:08 UTC, SvetaKo submitted a review, later dismissed
ok

2019-05-08 12:09 UTC, JonasChair approved these changes
LGBT

2019-05-08 12:10 UTC, Tokenas commented
LGTM

2019-05-08 12:16 UTC, petraspk submitted a review, later dismissed

2019-05-08 12:16 UTC, JonasChair commented on js/function.js
> -    var HTML = '';
Missing ";" (kabliataskis)

2019-05-08 12:25 UTC, JonasChair requested changes
Missing checks for elements of the incoming Array.
Make missing elements non visible? / set important emelents

2019-05-09 10:52 UTC, JonasChair approved these changes

2019-05-09 10:53 UTC, merged