Footer
front-end-by-rimantas/7-grupe-portfolio pull request #25
Opened 2019-05-09 13:48 UTC by JonasChair

Static content and the icon generation with JS.

2019-05-09 15:24 UTC, belauzas requested changes

2019-05-09 15:24 UTC, belauzas commented on js/function.js
> +    for(; position < data.length; position++){
Veikia.. Variantas.. Tačiau dažniausiai iteracijos kintamasis inicijuojamas vietoje. Funkcijos pradžioje to daryti neverta.
Vietoje "position", naudočiau "i" kintamojo pavadinimą.

2019-05-09 15:24 UTC, belauzas commented on js/function.js
> +            continue
Galima be kablelio, tačiau fainiau arba visur naudoti, arba niekur... bet ne kaip papuola - vienodi (asmeniniai arba komandiniai) įpročiai mažina klaidos tikimybę.

2019-05-09 15:24 UTC, belauzas commented on js/function.js
> +        HTML += '<a href="'+icon.url+'" class="fa fa-'+icon.name+'"/>'
taip pat kabletaškis

2019-05-10 11:49 UTC, belauzas requested changes

2019-05-10 11:49 UTC, belauzas commented on js/function.js
> +    for(i = 0; i < data.length; i++){
"i" turi būti inicijuotas, kitaip bus "use strict" error'as

2019-05-10 12:28 UTC, JonasChair commented on js/function.js
> +    for(i = 0; i < data.length; i++){
Fixed

2019-05-10 14:21 UTC, belauzas approved these changes
LGTM

2019-05-13 09:51 UTC, merged