Contact me
front-end-by-rimantas/7-grupe-portfolio pull request #26
Opened 2019-05-10 13:55 UTC by JonasChair

Static form plus contact information generation with JS.

Also noticed a console output from debuging in JS cleaned it up.

2019-05-10 14:26 UTC, belauzas requested changes

2019-05-10 14:26 UTC, belauzas commented on js/function.js
> +                console.log('bam');
Reikėtų šiek tiek išsamesnės žinutės :)

2019-05-10 14:26 UTC, belauzas commented on js/data.js
> +var contacts = [
Objekte, jei pridėsiu p3 ir t.t., tai tavo funkcija nebus pasiruošusi jį priimti, tad reikia perdaryti, taip, jog objektas iš savęs apibūdina vieną šį kontaktinės informacijos blokelį dar lanksčiau, t.y. neribotas kiekis pasirinktam tipui.

2019-05-10 14:26 UTC, belauzas commented on js/function.js
> +        HTML+= '<div class="contact-info">\
Atnaujinti pagal pakeisto objekto struktūrą (komentaras prie data.js failo).

2019-05-10 17:08 UTC, JonasChair commented on js/function.js
> +                console.log('bam');
Ai čia debuginau ir užmiršau ištrint patvarkysim :)

2019-05-13 09:49 UTC, belauzas submitted a review, later dismissed
LGTM

2019-05-13 09:54 UTC, belauzas approved these changes
LGTM

2019-05-13 09:54 UTC, merged