Testimonials 2
front-end-by-rimantas/7-grupe-portfolio pull request #55
Opened 2019-05-21 12:25 UTC by belauzas

2019-05-21 12:26 UTC, Tokenas commented
ok

2019-05-21 12:26 UTC, Tokenas submitted a review, later dismissed

2019-05-22 08:09 UTC, JonasChair requested changes

2019-05-22 08:09 UTC, JonasChair commented on js/function.js
> +        HTML += '<div class="item" style="width: 20%;">\
I think the item width should be calculated, because if we will have a different amount of items everything will fall apart.

2019-05-22 08:09 UTC, JonasChair commented on js/function.js
> +    list.style.marginLeft = '-200%';
Not sure but maybe should also be calculated?

2019-05-27 07:11 UTC, SvetaKo commented
LGTM

2019-05-27 07:12 UTC, SvetaKo submitted a review, later dismissed
LGTM

2019-05-27 11:06 UTC, JonasChair approved these changes

2019-05-27 11:06 UTC, merged